---
# Source: artifactory/templates/artifactory-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: artifactory
    chart: artifactory-7.12.4
    component: artifactory
    heritage: Tiller
    release: artifactory
  name: artifactory-artifactory
