---
# Source: artifactory/templates/artifactory-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: artifactory
    chart: artifactory-7.12.4
    component: artifactory
    heritage: Tiller
    release: artifactory
  name: artifactory-artifactory
subjects:
- kind: ServiceAccount
  name: artifactory-artifactory
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: artifactory-artifactory
