---
# Source: artifactory/templates/artifactory-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-artifactory
  labels:
    app: artifactory
    chart: artifactory-7.12.4
    heritage: Tiller
    release: artifactory
type: Opaque
data:
  master-key: "RkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRg=="
