---
# Source: artifactory/templates/nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: artifactory-artifactory-nginx
  labels:
    app: artifactory
    chart: artifactory-7.12.4
    component: nginx
    heritage: Tiller
    release: artifactory
spec:
  type: LoadBalancer
  
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginxhttp
  - port: 443
    targetPort: 443
    protocol: TCP
    name: artifactoryhttps
  selector:
    app: artifactory
    component: nginx
    release: artifactory
