---
# Source: artifactory/charts/postgresql/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifactory-postgresql
  labels:
    app: artifactory-postgresql
    chart: "postgresql-0.9.5"
    release: "artifactory"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: artifactory-postgresql
    spec:
      containers:
      - name: artifactory-postgresql
        image: "postgres:9.6.11"
        imagePullPolicy: ""
        args:
          - -c
          - 'max_connections=1500'
        env:
        - name: POSTGRES_USER
          value: "artifactory"
          # Required for pg_isready in the health probes.
        - name: PGUSER
          value: "artifactory"
        - name: POSTGRES_DB
          value: "artifactory"
        - name: POSTGRES_INITDB_ARGS
          value: ""
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: artifactory-postgresql
              key: postgres-password
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data/pgdata
          subPath: postgresql-db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: artifactory-postgresql
