---
# Source: artifactory/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-postgresql
  labels:
    app: artifactory-postgresql
    chart: "postgresql-0.9.5"
    release: "artifactory"
    heritage: "Tiller"
type: Opaque
data:
  
  postgres-password: "TlFLeURJemp1MQ=="
  
